### ISSUE TITLE
We should have a setup script!

### ISSUE THREAD

**Issue by sebastianmeisner** [ReconOS/reconos#3]
Setting up a ReconOS development system is a tedious task. While the [tutorial](http://www.reconos.de/gettingstarted/tutorial/) is a good start and documentation, it still takes long and it is easy to forget a step and run into a long search for errors. This is a show stopper for new ReconOS developers and should be changed!

On the other hand, most of the steps are easily automatable. so why not have a setup script?

- I would suggest a python or bash script. 
- It should first check all prerequisites like git, system enviroment etc.
- Then create the working directory $WD
- checkout all needed git repositories (with the last known working tag! _important!_ )
- build all stuff
- create and populate NFS directory
- etc. etc.

What are your thoughts about this?

**Comment by kolrami** [comment]
Hi @thombaaang, I assigned this task to you. I think you already did this and you might want to resolve it if you are done.

**Comment by thombaaang** [comment]
This is done for now. I only tested it on Ubuntu 14.04 LTS thus far.
