### ISSUE TITLE
Configurable Clock Frequency for Hardware Threads

### ISSUE THREAD

**Issue by kolrami** [ReconOS/reconos#6]
- Implement hardware component which generates an arbitrary clock frequency and allows reconfiguration of it at runtime. We can use the resources inside a CMT, e.g. PLL and MMCM, which allow reconfiguration through a DRP and need to provide an AXI interface to the processor.
- Add configuration options to allow specification of clocks and their usages. We want to add different clocks with predefined frequencies and generate an appropriate hardware project using RDK.
- Implement an easy to use API to change the frequency of a clock at runtime.
- Add a demonstration to, e.g. the sort demo.

**Comment by kolrami** [comment]
Clock can be configured and used as follows:

```
[Clock@Threads]
ClockSource = dynamic
ClockFreq = 120000000

[HwSlot@SortDemo(0:1)]
Id = 0
Clock = Threads
```

Furthermore, you need to set the `SystemClock` in the `General` section to a valid clock.

Reconfiguration at runtime is possible via automatically generated calls, e.g. `int reconos_clock_<ClockName>_set(int freqkHz)`. You can pass the wanted frequency in kHz and will get the real configured clock returned (i.e. not all clocks are possible by the hardware, dependent on the static configured clock).

**Comment by sebastianmeisner** [comment]
Is this already in the repo? DId you do a seperate demo for testing clock frequency settings?

I extendend the scripts for vivado and would like to test the dynamic clocking functionality now...

**Comment by kolrami** [comment]
As I wrote in my E-Mail to you, it is checked in and already used in the normal SortDemo application. To test it, it should be enough to change the build.cfg there to use Vivado instead of ISE.

**Comment by sebastianmeisner** [comment]
Oh, sorry, you are right! I'll test it and adapt my TCL scripts so that it works with Vivado!
