### ISSUE TITLE
HW slot dt flags are not reset

### ISSUE THREAD

**Issue by Lien182** [ReconOS/reconos#8]
Hi,
i tried to use ReconOS for dynamic partial reconfiguration, but it seems that there is an issue with the resetting of the "slot->dt_flags" -flags DELEGATE_FLAG_PAUSE_SYSCALLS and DELEGATE_FLAG_SUSPEND after resuming. Because of that, requests by the hardware thread through the OSIF interface are ignored by the delegated thread and the HW thread remains in a blocking state.

As a workaround, I added 	
slot->dt_flags &= ~DELEGATE_FLAG_PAUSE_SYSCALLS;
slot->dt_flags &= ~DELEGATE_FLAG_SUSPEND;

in the "hwslot_resumethread" function after the hardware reset procedure, which worked for me. 

Greetings, 
Christian

**Comment by kolrami** [comment]
Hi @Lien182, if I remember properly the semantic of the flags was as follows:

- `DELEGATE_FLAG_SUSPEND`: This is set when you call `reconos_thread_suspend`. It indicates to the delegate thread that the hardware thread should be suspended. It causes the `hwt_signal` to be raised which is then processed by the hardware thread. This flag is then resetted as soon as the delegate thread has processed it.
- `DELEGATE_FLAG_PAUSE_SYSCALLS`: This is also set when suspending a thread. It indicates that all syscalls should be caused. It is actually resetted in the delegate thread in `OSIF_CMD_THREAD_GET_STATE_ADDR`.

So I think the normal flow was intended to be: issue pause -> set signal -> hardware thread exits -> thread resumes -> get state address is called -> normal operation. That should cause the thread to run again, but I admit that it seems to be quite easy to break. In case we reset the flags also in the `hwslot_resumethread` I think we just need to make sure that we are in a reasonable state again.
