### ISSUE TITLE
demo compile error

### ISSUE THREAD

**Issue by casmac** [ReconOS/reconos#9]
I am trying to use reconOS V4 on a xilinx board. When I follow the demo compilation procedure, I keep getting this error message:

reconOSmyir/reconos/demos/sort_demo$ rdk export_sw
reconOSmyir/reconos/demos/sort_demo$ rdk export_hw
export_hw_vivado
Using template directory ref_linux_zedboard_d_timer_vivado_2017.1
Calling TCL script to generate Vivado IP Repository
/bin/sh: 2: source: not found
/bin/sh: 4: vivado: not found
[RDK] Generation of Vivado IP repository failed. Maybe you specified unknown components in build.cfg?

  Any idea on how to fix this? Thank you !
  regards,
----
the build.cfg file, not much changed --->
[General]
Name = SortDemo
TargetBoard = zedboard,d
TargetPart = xc7z020clg484-1
ReferenceDesign = timer
TargetOS = linux
TargetXil = vivado,2017.1
SystemClock = System
CFlags = -I $(RECONOS)/linux/tools/timer
LdFlags = -L $(RECONOS)/linux/tools/timer -ltimer

**Comment by alexriv44** [comment]
This is due to a bad sourcing in the script export.py in reconos/tools/_pypack/reconos/scripts/hw/
I don't find yet how to solved it directly in the script but you may do the sourcing manually.

Use this following command before starting to export : 
source /opt/Xilinx/Vivado/2017.1/settings64.sh

**Comment by fpjentzsch** [comment]
Fixed in https://github.com/ReconOS/reconos/pull/10
